server:
  port: 9001
spring:
  application:
    name: supermarket-customer
  boot:
    admin:
      client:
        #admin  server端地址
        url: http://127.0.0.1:8000
        username: monitor
        password: 123123
        instance:
          service-base-url: http://127.0.0.1:${server.port}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo-supermarket-customer?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&useUnicode=false&rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: dudu.20190808
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated  # 必须配置这个才会确认回调
    publisher-returns: true

# info信息会显示到SpringBootAdmin的server端，这里取的是pom文件中的数据
info:
  name: ${spring.application.name}
  description: @project.description@
  version: @project.version@
  groupId: @project.groupId@
  artifactId: @project.artifactId@

#Actuator配置：暴露敏感路径，默认情况下，敏感路径并不暴露
management:
  endpoints:
    web:
      exposure:
        # 暴露xxx端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
        include: '*'
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: ALWAYS
logging:
  file:
    path: logs/