server:
  port: 8001
spring:
  application:
    name: dudu-register
  boot:
    admin:
      client:
        #admin  server端地址
        url: http://127.0.0.1:8000
        #对应server端的账号密码，不配置就监控不到这个client。
        username: monitor
        password: 123123
        instance:
          service-base-url: http://127.0.0.1:${server.port}
  security:
    user:
      name: register
      password: 123123
eureka:
  instance:
    hostname: 127.0.0.1
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 60
    prefer-ip-address: true
  client:
    # 表示自己就是注册中心，不用注册自己
    registerWithEureka: false
    # false表示自己就是注册中心，不用去注册中心获取其他服务的地址
    fetchRegistry: false
    instance-info-replication-interval-seconds: 30
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# info信息会显示到SpringBootAdmin的server端，这里取的是pom文件中的数据
info:
  name: ${spring.application.name}
  description: ${app.info.description}
  version: @project.version@
  groupId: @project.groupId@
  artifactId: @project.artifactId@

#Actuator配置：暴露敏感路径，默认情况下，敏感路径并不暴露
management:
  endpoints:
    web:
      exposure:
        # 暴露xxx端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
        include: '*'
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: ALWAYS

app:
  info:
    description: 注册机

logging:
  file:
    path: logs/
